### ISSUE TITLE
坏掉了 QwQ

### ISSUE THREAD

**Issue by tiger0132** [ouuan/Code-Disturber#1]
命令：`python3 disturb.py 1.cpp emoji.json 1 0`

`1.cpp` 的内容：

```cpp
int a, b = 1.8e-12f;
int main() { a += b; }
```

您的 tokenizer 把 `1.8e-12f` 当成了 **`1`** **`.`** **`8e`** **`-`** **`12f`** 这些 token。但是如果这样替换，这份代码是会 CE 的：

```cpp
#define x 1
#define y 8e
#define z 12f
int a, b = x.y-z;
int main() { a += b; }
```

**Comment by ouuan** [comment]
~~本项目不保证对任意代码可用~~

**Comment by tiger0132** [comment]
（写个 tokenizer 呗

**Comment by ouuan** [comment]
> （写个 tokenizer 呗

（欢迎 pr 修锅.webp）
