### ISSUE TITLE
怎么生成的代码没回车鸭QAQ

### ISSUE THREAD

**Issue by StudyingFather** [ouuan/Code-Disturber#2]
头文件下面的东西全部压成一两行了...极其严重影响观感QAQ

见[这个提交](https://loj.ac/submission/408348)。

~~别问我为什么拿代码这么长的一道题测试（逃~~

**Comment by tiger0132** [comment]
这样效果好嘛，本来就是混淆

**Comment by StudyingFather** [comment]
> 这样效果好嘛，本来就是混淆

用emoji的目的就是获得比较好的观感吧QAQ

本来还想欣赏一下自己300多行的毒瘤代码会变成怎样漂亮的样子呢（逃

**Comment by ouuan** [comment]
可能 fix 了。

~~别找我要缩进~~，如果不是 emoji 的话 LOJ 可以格式化（我也不知道为什么 emoji 不能格式化..）
